config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  root to: 'items#index'
  resources :users, only: [:show, :update] do
    resources :order_records, only: [:index]
  end
  resources :items do
    resources :orders, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :order_records

  with_options presence: true do
    validates :nickname
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角かな/カナ/漢字で入力してください', allow_blank: true }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角かな/カナ/漢字で入力してください', allow_blank: true }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カナで入力してください', allow_blank: true }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カナで入力してください', allow_blank: true }
    validates :birth_date
    validates :password_confirmation, on: :create
  end
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字を含めて入力してください', allow_blank: true }
  validates :profile, length: { maximum: 200 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :profile])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]

  def show
    @items = @user.items
    @order_record = OrderRecord.all
  end

  def update
    @user.update(update_params)
    redirect_to action: :show
    return
  end

  private

  def update_params
    params.require(:user).permit(:profile)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>

<%# プロフィール部分 %>
<div class='user-show-main'>
  <div class='user-shows'>
    <div class='profile-main'>
      <div class='profile-name'>
        <div class='profile-nickname'><%= "#{@user.nickname}さんのプロフィール" %></div>
        <% if user_signed_in? %>
          <% if current_user.id == @user.id %>
              <%= image_tag("edit_button.png", class:"edit-bottom",id:'edit-bottom') %>
          <% end %>
        <% end %>
      </div>
      
      <div class='profile-content'>
      <%# 編集できる様にする %>
        <div class='profile-text'>
          <div class='profile-text-content'><%= @user.profile %></div>
        </div>
      </div>
      <%# 注文履歴を確認できるリンク・current_userしか表示されないようにする%>
      <% if user_signed_in? %>
        <% if current_user.id == @user.id %>
          <div class='order-record'>
            <%= link_to '注文履歴の確認', user_order_records_path(current_user.id), class:'order-info' %>
            <%= image_tag("order.png", class:"order-bottom",id:'order-bottom') %>
          </div>
        <% end %>
      <% end %>
    </div>
<%# /プロフィール部分 %>

<%# 自分の出品した商品の一覧 %>
    <div class='list-item-main'>
      <div class='list-item-title'>
        <div>出品商品一覧</div>
      </div>
      <div class='list-items'>
         <% @items.each do |item| %>
         <div class='list-item'>
          <div class='item-img-content'>
            <%= link_to image_tag(item.image, class:'list-image'),item_path(item.id) %>
            <% if @order_record.exists?(item_id: item.id) %>
              <div class="sold-out">
                <span>Sold Out!!</span>
              </div>
            <% end %>
          </div>
            <ul class ='list-info'>
              <li><%= "商品名：#{item.name}" %></li>
              <li><%= "価格：#{item.price}" %></li>
            </ul>
         </div>
        <% end %>
      </div>
    </div>
<%# /自分の出品した商品の一覧 %>
  </div>
</div>

<%# モーダルコンテンツ%>
<div id="modal", class="modal">
  <div class="modal-content">
    <%= form_with model: @user, class:"edit-area", local: true do |f| %>
      <div class='modal-wrap'>
        <label class="modal-title">プロフィールの編集</label>
      </div>
      <%= f.text_area :profile, class:"profile-input", id:"profile-input", maxlength:200 %>
        <div class="bottoms">
          <%= f.submit "更新する" ,id:"editBtn" ,class:"edit" %>
          <%= f.submit "閉じる",id:"closeBtn" ,class:"close" %>
        </div>
    <% end %>
  </div>
</div>
<%# /モーダルコンテンツ%>

<%= render "shared/footer" %>